blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/about-private-reporting-of-security-vulnerabilities
    about: Please use a private channel for security issues whenever possible.
