#!/usr/bin/env swift

//
//  GeneratePrefixAliases.swift
//  PrismUI
//
//  Created by Rafael Escaleira on 09/04/26.
//
//  Script para gerar automaticamente typealiases com prefixo personalizado
//
//  Uso:
//  ```bash
//  swift Scripts/GeneratePrefixAliases.swift <PREFIX> <OUTPUT_PATH>
//  ```
//
//  Exemplo:
//  ```bash
//  swift Scripts/GeneratePrefixAliases.swift Zenith ./Sources/MyApp/ZenithAliases.swift
//  ```
//

import Foundation

// MARK: - Configuration

struct Configuration {
    let prefix: String
    let outputURL: URL
    let copyright: String
    let createdDate: String
    let creator: String

    init(prefix: String, outputURL: URL) {
        self.prefix = prefix
        self.outputURL = outputURL
        self.copyright = """
        //
        //  \(prefix)UIPrefixAliases.swift
        //  PrismUI
        //
        //  Generated by GeneratePrefixAliases.swift
        //

        """
        self.createdDate = DateFormatter.localizedString(from: Date(), dateStyle: .medium, timeStyle: .none)
        self.creator = "PrismUI Prefix Generator"
    }
}

// MARK: - Type Definition

struct TypeDefinition {
    let name: String
    let category: String

    static let allTypes: [TypeDefinition] = [
        // Atoms
        .init(name: "PrismButton", category: "Atoms"),
        .init(name: "PrismText", category: "Atoms"),
        .init(name: "PrismTextField", category: "Atoms"),
        .init(name: "PrismSymbol", category: "Atoms"),
        .init(name: "PrismSpacer", category: "Atoms"),
        .init(name: "PrismVStack", category: "Atoms"),
        .init(name: "PrismHStack", category: "Atoms"),
        .init(name: "PrismZStack", category: "Atoms"),
        .init(name: "PrismLazyList", category: "Atoms"),
        .init(name: "PrismList", category: "Atoms"),
        .init(name: "PrismHorizontalList", category: "Atoms"),
        .init(name: "PrismAsyncImage", category: "Atoms"),
        .init(name: "PrismShape", category: "Atoms"),
        .init(name: "PrismSection", category: "Atoms"),
        .init(name: "PrismLabel", category: "Atoms"),
        .init(name: "PrismTabView", category: "Atoms"),

        // Molecules
        .init(name: "PrismTag", category: "Molecules"),
        .init(name: "PrismCarousel", category: "Molecules"),
        .init(name: "PrismPrimaryButton", category: "Molecules"),
        .init(name: "PrismSecondaryButton", category: "Molecules"),
        .init(name: "PrismBodyText", category: "Molecules"),
        .init(name: "PrismFootnoteText", category: "Molecules"),
        .init(name: "PrismCurrencyTextField", category: "Molecules"),
        .init(name: "PrismNavigationView", category: "Molecules"),
        .init(name: "PrismBrowserView", category: "Molecules"),
        .init(name: "PrismVideoView", category: "Molecules"),

        // Accessibility
        .init(name: "PrismAccessibilityProperties", category: "Accessibility"),
        .init(name: "PrismAccessibilityConfig", category: "Accessibility"),
        .init(name: "PrismAccessibility", category: "Accessibility"),
        .init(name: "PrismAccessibilityAction", category: "Accessibility"),
        .init(name: "PrismAccessibilityBuilder", category: "Accessibility"),
        .init(name: "PrismAccessibilityHint", category: "Accessibility"),

        // Styles & Tokens
        .init(name: "PrismColor", category: "Styles & Tokens"),
        .init(name: "PrismSpacing", category: "Styles & Tokens"),
        .init(name: "PrismRadius", category: "Styles & Tokens"),
        .init(name: "PrismSize", category: "Styles & Tokens"),
        .init(name: "PrismGradient", category: "Styles & Tokens"),
        .init(name: "PrismSemanticColors", category: "Styles & Tokens"),
        .init(name: "PrismDesignTokens", category: "Styles & Tokens"),
        .init(name: "SpacingToken", category: "Styles & Tokens"),
        .init(name: "RadiusToken", category: "Styles & Tokens"),
        .init(name: "FontSizeToken", category: "Styles & Tokens"),
        .init(name: "MotionToken", category: "Styles & Tokens"),
        .init(name: "Breakpoint", category: "Styles & Tokens"),

        // Protocols
        .init(name: "PrismThemeProtocol", category: "Protocols"),
        .init(name: "PrismColorProtocol", category: "Protocols"),
        .init(name: "PrismSpacingProtocol", category: "Protocols"),
        .init(name: "PrismRadiusProtocol", category: "Protocols"),
        .init(name: "PrismSizeProtocol", category: "Protocols"),
        .init(name: "PrismFontProtocol", category: "Protocols"),
        .init(name: "PrismFontFamilyProtocol", category: "Protocols"),
        .init(name: "PrismTextFieldMask", category: "Protocols"),
        .init(name: "PrismTextFieldConfiguration", category: "Protocols"),
        .init(name: "PrismUIMock", category: "Protocols"),

        // Errors & Enums
        .init(name: "PrismUIError", category: "Errors & Enums"),
        .init(name: "PrismTextInputAutocapitalization", category: "Errors & Enums"),
        .init(name: "PrismTextFieldContentType", category: "Errors & Enums"),
    ]
}

// MARK: - Generator

class AliasGenerator {
    private let config: Configuration

    init(config: Configuration) {
        self.config = config
    }

    func generate() -> String {
        var output = ""

        // Header
        output += "//\n"
        output += "//  \(config.prefix)UIPrefixAliases.swift\n"
        output += "//  PrismUI\n"
        output += "//\n"
        output += "//  Generated by \(config.creator) on \(config.createdDate).\n"
        output += "//\n"
        output += "//  Arquivo de typealiases para personalização de prefixo do Design System.\n"
        output += "//  Este arquivo foi gerado automaticamente pelo script GeneratePrefixAliases.swift\n"
        output += "//\n"
        output += "//  PARA USAR: Importe este arquivo no seu projeto e use os aliases com prefixo '\(config.prefix)'\n"
        output += "//\n"
        output += "//  Exemplo:\n"
        output += "//  ```swift\n"
        output += "//  import PrismUI\n"
        output += "//\n"
        output += "//  var button: \(config.prefix)Button\n"
        output += "//  var text: \(config.prefix)Text\n"
        output += "//  ```\n"
        output += "//\n"
        output += "\n"
        output += "import SwiftUI\n"
        output += "\n"

        // Group types by category
        let groupedTypes = Dictionary(grouping: TypeDefinition.allTypes) { $0.category }

        // Generate typealiases for each category
        for category in groupedTypes.keys.sorted() {
            let types = groupedTypes[category]!
            output += "// MARK: - \(category)\n"
            output += "\n"

            for type in types {
                let aliasName = type.name.replacingOccurrences(of: "Prism", with: config.prefix)
                output += "public typealias \(aliasName) = \(type.name)\n"
            }

            output += "\n"
        }

        // View Modifiers Extensions
        output += "// MARK: - View Modifiers Extensions\n"
        output += "\n"
        output += "extension View {\n"
        output += "    // MARK: - Accessibility\n"
        output += "\n"
        output += "    /// Aplica prefixo personalizado às propriedades de acessibilidade\n"
        output += "    public func \(config.prefix.lowercased())(accessibility properties: PrismAccessibilityProperties) -> some View {\n"
        output += "        prism(accessibility: properties)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Atalho para definir apenas testID com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(testID: String) -> some View {\n"
        output += "        prism(testID: testID)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica propriedades de acessibilidade usando builder pattern com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(accessibility builder: (PrismAccessibilityConfig) -> PrismAccessibilityConfig) -> some View {\n"
        output += "        prism(accessibility: builder)\n"
        output += "    }\n"
        output += "\n"
        output += "    // MARK: - Style Modifiers\n"
        output += "\n"
        output += "    /// Aplica cor de fundo com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(background style: PrismColor) -> some View {\n"
        output += "        prism(background: style)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica cor de tint com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(tint color: PrismColor) -> some View {\n"
        output += "        prism(tint: color)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica cor de foreground com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(color: PrismColor) -> some View {\n"
        output += "        prism(color: color)\n"
        output += "    }\n"
        output += "\n"
        output += "    // MARK: - Environment Modifiers\n"
        output += "\n"
        output += "    /// Aplica tema com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(theme: PrismThemeProtocol) -> some View {\n"
        output += "        prism(theme: theme)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica locale com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(locale: PrismLocale) -> some View {\n"
        output += "        prism(locale: locale)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica color scheme com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(colorScheme: ColorScheme? = nil) -> some View {\n"
        output += "        prism(colorScheme: colorScheme)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica estado de loading com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(loading: Bool) -> some View {\n"
        output += "        prism(loading: loading)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica estado de disabled com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(disabled: Bool) -> some View {\n"
        output += "        prism(disabled: disabled)\n"
        output += "    }\n"
        output += "\n"
        output += "    // MARK: - Text Modifiers\n"
        output += "\n"
        output += "    /// Aplica alinhamento de texto com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(alignment: TextAlignment) -> some View {\n"
        output += "        prism(alignment: alignment)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica fonte com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(\n"
        output += "        font: Font = .body,\n"
        output += "        weight: Font.Weight? = nil,\n"
        output += "        design: Font.Design? = nil\n"
        output += "    ) -> some View {\n"
        output += "        prism(font: font, weight: weight, design: design)\n"
        output += "    }\n"
        output += "\n"
        output += "    // MARK: - Size & Spacing Modifiers\n"
        output += "\n"
        output += "    /// Aplica tamanho com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(\n"
        output += "        width: PrismSize? = nil,\n"
        output += "        height: PrismSize? = nil,\n"
        output += "        alignment: Alignment = .center\n"
        output += "    ) -> some View {\n"
        output += "        prism(width: width, height: height, alignment: alignment)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica padding com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())Padding(\n"
        output += "        _ edges: Edge.Set = .all,\n"
        output += "        _ spacing: PrismSpacing = .medium\n"
        output += "    ) -> some View {\n"
        output += "        prismPadding(edges, spacing)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica padding com prefixo personalizado (todas as bordas)\n"
        output += "    public func \(config.prefix.lowercased())Padding(\n"
        output += "        _ spacing: PrismSpacing = .medium\n"
        output += "    ) -> some View {\n"
        output += "        prismPadding(spacing)\n"
        output += "    }\n"
        output += "\n"
        output += "    // MARK: - Background Modifiers\n"
        output += "\n"
        output += "    /// Aplica background padrão com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())Background() -> some View {\n"
        output += "        prismBackground()\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica background secundário com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())BackgroundSecondary() -> some View {\n"
        output += "        prismBackgroundSecondary()\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica background de row com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())BackgroundRow() -> some View {\n"
        output += "        prismBackgroundRow()\n"
        output += "    }\n"
        output += "\n"
        output += "    // MARK: - Effect Modifiers\n"
        output += "\n"
        output += "    /// Aplica efeito glow com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())Glow(for color: Color? = nil) -> some View {\n"
        output += "        prismGlow(for: color)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica efeito de símbolo com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())Symbol<T: IndefiniteSymbolEffect & SymbolEffect>(\n"
        output += "        effect: T,\n"
        output += "        options: SymbolEffectOptions = .default,\n"
        output += "        isActive: Bool = true\n"
        output += "    ) -> some View {\n"
        output += "        prismSymbol(effect: effect, options: options, isActive: isActive)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica efeito skeleton com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())Skeleton() -> some View {\n"
        output += "        prismSkeleton()\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica efeito parallax com prefixo personalizado (iOS apenas)\n"
        output += "    public func \(config.prefix.lowercased())Parallax(width: PrismSize? = nil, height: PrismSize?) -> some View {\n"
        output += "        prismParallax(width: width, height: height)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica efeito de confetti com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())Confetti(\n"
        output += "        amount: Int = 30,\n"
        output += "        seconds: Int = 4,\n"
        output += "        isActive: Bool\n"
        output += "    ) -> some View {\n"
        output += "        prismConfetti(amount: amount, seconds: seconds, isActive: isActive)\n"
        output += "    }\n"
        output += "\n"
        output += "    // MARK: - Shape & Clip Modifiers\n"
        output += "\n"
        output += "    /// Aplica clip de shape com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(clip shape: PrismShape) -> some View {\n"
        output += "        prism(clip: shape)\n"
        output += "    }\n"
        output += "\n"
        output += "    // MARK: - Screen & Display Modifiers\n"
        output += "\n"
        output += "    /// Aplica observação de screen com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())ScreenObserve(minimumWidthScreen: CGFloat = 430) -> some View {\n"
        output += "        prismScreenObserve(minimumWidthScreen: minimumWidthScreen)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica browser sheet com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())Browser(url: Binding<URL?>) -> some View {\n"
        output += "        prismBrowser(url: url)\n"
        output += "    }\n"
        output += "\n"
        output += "    // MARK: - Preview Modifiers\n"
        output += "\n"
        output += "    /// Aplica preview com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())Preview(\n"
        output += "        layout: PreviewLayout,\n"
        output += "        orientation: InterfaceOrientation,\n"
        output += "        colorScheme: ColorScheme,\n"
        output += "        locale: PrismLocale\n"
        output += "    ) -> some View {\n"
        output += "        prismPreview(\n"
        output += "            layout: layout,\n"
        output += "            orientation: orientation,\n"
        output += "            colorScheme: colorScheme,\n"
        output += "            locale: locale\n"
        output += "        )\n"
        output += "    }\n"
        output += "\n"
        output += "    // MARK: - Conditional Modifiers\n"
        output += "\n"
        output += "    /// Aplica transformação condicional com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())<Content: View>(\n"
        output += "        if condition: Bool,\n"
        output += "        transition: AnyTransition = .scale,\n"
        output += "        animation: Animation? = .linear,\n"
        output += "        transform: (Self) -> Content\n"
        output += "    ) -> some View {\n"
        output += "        prism(if: condition, transition: transition, animation: animation, transform: transform)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica transformação condicional com item opcional\n"
        output += "    public func \(config.prefix.lowercased())<Content: View, Value>(\n"
        output += "        item value: Value?,\n"
        output += "        transform: (Self, Value) -> Content\n"
        output += "    ) -> some View {\n"
        output += "        prism(item: value, transform: transform)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica transformação condicional com else\n"
        output += "    public func \(config.prefix.lowercased())<Content: View, ElseContent: View>(\n"
        output += "        if condition: Bool,\n"
        output += "        transform: (Self) -> Content,\n"
        output += "        `else`: ((Self) -> ElseContent)? = nil\n"
        output += "    ) -> some View {\n"
        output += "        prism(if: condition, transform: transform, else: `else`)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica transformação condicional com item opcional e else\n"
        output += "    public func \(config.prefix.lowercased())<Content: View, Value, ElseContent: View>(\n"
        output += "        item value: Value?,\n"
        output += "        transform: (Self, Value) -> Content,\n"
        output += "        `else`: ((Self) -> ElseContent)? = nil\n"
        output += "    ) -> some View {\n"
        output += "        prism(item: value, transform: transform, else: `else`)\n"
        output += "    }\n"
        output += "}\n"

        return output
    }

    func write() throws {
        let directory = config.outputURL.deletingLastPathComponent()
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)

        let content = generate()
        try content.write(to: config.outputURL, atomically: true, encoding: .utf8)

        print("✅ Arquivo gerado com sucesso: \(config.outputURL.path)")
        print("📊 Total de typealiases: \(TypeDefinition.allTypes.count)")
    }
}

// MARK: - Main

func main() {
    let arguments = CommandLine.arguments

    guard arguments.count >= 2 else {
        print("❌ Uso: swift GeneratePrefixAliases.swift <PREFIX> [OUTPUT_PATH]")
        print("")
        print("Exemplos:")
        print("  swift GeneratePrefixAliases.swift Zenith")
        print("  swift GeneratePrefixAliases.swift App ./MyApp/Aliases/AppPrefixAliases.swift")
        print("")
        print("O arquivo será gerado em:")
        print("  ./Sources/PrismUI/Exports/<PREFIX>UIPrefixAliases.swift (padrão)")
        exit(1)
    }

    let prefix = arguments[1]
    let outputPath: String

    if arguments.count >= 3 {
        outputPath = arguments[2]
    } else {
        // Caminho relativo ao diretório atual
        outputPath = "./\(prefix)UIPrefixAliases.swift"
    }

    let outputURL = URL(fileURLWithPath: outputPath)

    print("🚀 Gerando typealiases com prefixo '\(prefix)'...")
    print("📁 Output: \(outputURL.path)")
    print("")

    let config = Configuration(prefix: prefix, outputURL: outputURL)
    let generator = AliasGenerator(config: config)

    do {
        try generator.write()
    } catch {
        print("❌ Erro ao gerar arquivo: \(error)")
        exit(1)
    }
}

main()
